services:
  forwarder:
    image: splunk/splunk:latest
    platform: linux/amd64
    container_name: splunk-forwarder
    hostname: forwarder
    environment:
      - SPLUNK_ROLE=splunk_heavy_forwarder
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_CLUSTER_MASTER_URL=${SPLUNK_CLUSTER_MASTER_URL:-splunk-cluster-master}
      - SPLUNK_INDEXER_URL=${SPLUNK_INDEXER_URL:-splunk-indexer}
      - SPLUNK_LICENSE_MASTER_URL=${SPLUNK_LICENSE_MASTER_URL:-splunk-license-master}
      - SPLUNK_DEPLOYMENT_SERVER=${SPLUNK_DEPLOYMENT_SERVER:-splunk-deployment-server}
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    networks:
      - splunk-net

networks:
  splunk-net:
    name: splunk-net
    driver: bridge
